import EmblaCarousel from "./EmblaCarousel";
import { EmblaOptionsType } from "embla-carousel";
import "./css/embla.css";

const OPTIONS: EmblaOptionsType = { loop: true };

const clientComments = [
  {
    title: "Real Estate Asset Monetization",
    image: "/Assetmonetization/usecase1.png",
    desc: "An investor has a commercial property portfolio, but needs liquidity to fund a new venture. Selling the properties directly would take time and reduce their value. As a solution, Epiidosis Investments creates an SPV to hold the properties and issue bonds backed by the assets. Investing in these instruments provides the developer with immediate liquidity. Revenue generated from the properties (e.g., rent) pays off the debt.",
  },
  {
    title: "Intellectual Property (IP) Monetization",
    image: "/Assetmonetization/usecase2.png",
    desc: "Technology companies own valuable patents and trademarks, but need capital to scale. The company does not want to sell its IP outright since it expects future growth. A SPV is created by Epiidosis Investments to hold IP assets, with securities or licenses backed by future revenues. While maintaining ownership of the company's intellectual property, investors provide the company with access to funds.",
  },
  {
    title: "Infrastructure Project Financing",
    image: "/Assetmonetization/usecase3.png",
    desc: "When a large infrastructure project is completed, such as a bridge, road, or airport, governments and businesses may need to refinance to settle construction debt or fund new projects. Epiidosis Investments' solution is to form an SPV to own infrastructure and issue bonds or equity instruments tied to future cash flows generated by the asset. Investors earn returns on these issuances, while debt can be repaid or new projects financed.",
  },
  {
    title: "Renewable Energy Asset Monetization",
    image: "/Assetmonetization/usecase4.png",
    desc: "In this case, a renewable energy company has several operating solar or wind farms but needs additional capital to expand. Epiidosis Investments creates an SPV to acquire energy assets and issue green bonds or asset-backed securities backed by future revenue from energy sales. As a result, the company can raise capital while the SPV manages the cash flow, providing investors with steady returns.",
  },
  {
    title: "Future Revenue Streams Monetization",
    image: "/Assetmonetization/usecase5.png",
    desc: "In this scenario, a company with a strong brand or product line expects significant future royalties but needs immediate funding in order to expand. In order to acquire these future royalties, Our team forms an SPV. The SPV issues securities to investors, backed by anticipated royalty streams. As a result, the firm receives a lump sum and the investors receive future income in return.",
  },
  {
    title: "Supply Chain Financing",
    image: "/Assetmonetization/usecase6.png",
    desc: "There are substantial receivables tied up in a large manufacturer's supply chain, which have a negative impact on its liquidity. In order to buy these receivables at a discount, our team creates a SPV. Upon receiving payments from these receivables, the SPV issues short-term commercial paper or other securities to investors. As a result, the manufacturer receives immediate working capital, and investors receive a return on their investments.",
  },
];

const generateSlides = (times: any) => {
  const slides = [];
  for (let i = 0; i < times; i++) {
    slides.push(...clientComments);
  }
  return slides;
};

const Slider = () => {
  const slides = generateSlides(1000); // Repeat the clientComments 10 times

  return (
    <>
    <div className="h-[550px] slider_bg relative mt-9" style={{
      fontFamily: "Lato, sans-serif",
    }}>
      <span className="red_circle bg-liver absolute hidden lg:block"></span>
      <EmblaCarousel slides={slides} options={OPTIONS} />
    </div>
    </>
  );
};

export default Slider;
